[build]
publish = ".next"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

[context.branch-deploy.environment]
  NODE_ENV = "development"